### ISSUE TITLE
Convert fractions in units to decimals

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#103]
convert fractions in units to decimals
if there are none then just ignore

**Comment by cerdamario13** [comment]
```yaml
wrangles:
  - convert.fraction_to_decimal:
      input: col1
      output: out1
      decimals: 4  -> optional
```

| col1                            | out1                               |
|:--------------------------------|:-----------------------------------|
| The length is 1/2 wide 1/3 high | The length is 0.5 wide 0.3333 high |
| the 1/2 panel is 3/4 inches     | the 0.5 panel is 0.75 inches       |
| the diameter is 1/3 meters      | the diameter is 0.3333 meters      |
