### ISSUE TITLE
New Wrangle: Validate

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#109]
Add a method to validate data as part of a recipe.

e.g.
```yaml
wrangles:
  - validate:
      <column name>:
          data_type: str
          min:
          max:
          regex_pattern:
```

Questions:
- How to deal with failure?
   - Raise error.
   - Flag failed rows somehow.
- Use a third partly library or implement ourselves?
