### ISSUE TITLE
Variables within strings don't work.

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#115]
Variables within strings don't seem to work.

```yml
file:
  name: ${filename}

file:
  name: file-${number}.xlsx
```
