### ISSUE TITLE
CKAN Connector

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#119]
Watsco idea: use APIs to transform data dictionary into a Excel Wrangles Map

**Comment by ChrisWRWX** [comment]
Added to v1.1.

Initial code finished. Able to read and write from/to the file store.

```yml
read:
  - ckan:
      api_key: <API KEY>
      host: https://ckan.example.com
      dataset: my-dataset
      file: file.csv

write:
  - ckan:
      api_key: <API KEY>
      host: https://ckan.example.com
      dataset: my-dataset
      file: file.csv # will replace file if it already exists
```

Need to research further interacting with the data store as opposed to the file store. Will add new issues for specific further refinements.
