### ISSUE TITLE
Product Description Writer - Recipe Only

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#120]
Genrating high quality, unique descriptions is needed by consumer companies, and even useful to hybrids that sell B2B & C. Let's start by creating templates (Q1) and then graduate to NLP generative models
```[tasklist]
### Outstanding Issues
- [ ] Incorporate template builder approach developed by Eric
- [ ] For now a 'Template Generator' is required. So either one of the input parameters needs to be the file (I don't think Chris likes this) or it's hardcoded into a specific instance of the jinja wrangle something like `jinja.description`

**Comment by ChrisWRWX** [comment]
Thomas to create initially as custom functions, then we can incorporate into the code base as a stock Wrangle.

Possible variations/functionality:

1. Passed in directly from the recipe.
```yml
wrangles:
  - custom.template:
      output: <column name>
      template: |
        <JINJA STUFF>
```

2. Passed in as a file.
```yml
wrangles:
  - custom.template:
      output: <column name>
      template: <filename>
```

3. Passed in as a column - each row would apply the template from the corresponding column in that row.
```yml
wrangles:
  - custom.template:
      output: <column name>
      template: <column name>
```
