### ISSUE TITLE
Upper Case Not Working

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#125]
when I ran upper in a recipe, I got NaNs all the way down.  Let me know if you can't repoduce this.

**Comment by ChrisWRWX** [comment]
Do you have some more context for this? What version of Wrangles are you using?

This recipe:
```yml
read:
  - test:
      rows: 5
      values:
        header: make upper case
      
wrangles:
  - convert.case:
      input: header
      case: upper

  - log: {}
```

Gives the expected output:
```
            header
0  MAKE UPPER CASE
1  MAKE UPPER CASE
2  MAKE UPPER CASE
3  MAKE UPPER CASE
4  MAKE UPPER CASE
```
