### ISSUE TITLE
Rename does not work with wildcards

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#138]
Rename does not work with wildcards

```yaml
# Does not work
  - rename:
      input: Attribute Value *
      output: Value *
```
