### ISSUE TITLE
Row based custom functions

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#144]
Add a simpler syntax for row based custom functions.

Function parameters must match column names.

```py
def add_numbers(val1, val2):
        return val1 + val2
```

```yaml
wrangles:
  - custom.add_numbers:
       output: val3
```
