### ISSUE TITLE
Create.jinja: allow spaces in column names

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#148]
This is currently not possible due to the way the data is passed as variables.

Replace with underscores prior to using??

**Comment by ChrisWRWX** [comment]
Added to v1.2. Keys must use an underscore instead of a space. This works even if the column header or dictionary key has a space.

```yaml
wrangles:
  - create.jinja:
      output: description
      template: 
         string: This is a {{length}} {{head_type}} screwdriver
```
