### ISSUE TITLE
Add alias to schema

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#152]
Add as a placeholder for storing YAML anchor/aliases so the validation doesn't highlight it as an error.

**Comment by ChrisWRWX** [comment]
Added as 

```yml
alias:
  - &string 'value'
  - key: &object
       key1: val1
       key2: val2
```
