### ISSUE TITLE
Allow custom run functions access to exception

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#163]
Allow an _error_ parameter that will pass the exception for custom functions.

```py
def handle_error(error: Exception):
   # error contains the Exception raised
```

```yml
run:
  on_failure:
    - custom.handle_error: {}
```
