### ISSUE TITLE
Allow period for run custom functions

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#164]
Allow period to work to allow recursively nested members

```py
class my_class:
  def my_function():
```

```yml
run:
  on_failure:
     - custom.my_class.my_function: {}
```
