### ISSUE TITLE
Allow one input and multiple outputs and model_id in custom wrangles?

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#170]
This will wrangle the same input for all outputs and model_ids

example:
```yaml
 - extract.custom:
      input: Name
      output:
        - Brands
        - Styles
        - Noun
      model_id:
        - $Brands}
        - ${Styles}
        - $Nouns}
```
