### ISSUE TITLE
Connector: Matrix Write

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#184]
Allow writing multiple outputs dynamically using variables.

```yml
write:
  - matrix:
      variables:
        filename: set(header)
        filename2: [a, b, c]
      write:
        - file:
            name: ${filename}-${filename2}.csv
            where: header = '${filename}'
```
