### ISSUE TITLE
Can we have a Write Wrangle?

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#185]
Currently, `write` is only written at the end of the recipe and after that, no wrangles can be performed. This will be a wrangle inside `wrangles` that has the same functionality as `write`.

e.g.

```yaml
read:
  - file: 
       name: particleColliderData.csv

wrangles:
  - clean.particleData:
       input: col1
  
# Write to any connector given the current dataFrame status
  - write:
       file: SeeWhatDataLooksLike.csv  # or any other connector
  
  - more.wrangles:
      input: col2

write:
  - file:
      name: FinalDataOut.csv

```

**Comment by ChrisWRWX** [comment]
Note: this is already available by using log.

```yml
wrangles:
  ...

  - log:
      write:
        - file:
            name: example.csv

  ...
```
