### ISSUE TITLE
Trim fails for input as string

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#188]
This is failing. Causes a key error, which suggests the string is being split and it's searching for individual characters as columns.

```yml
wrangles:
  - format.trim:
      input: <column>
```
