### ISSUE TITLE
SFTP Connector Run Action

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#190]
Add general run read/write actions similar to S3.

```yml
    - sftp.download_files:
        host: ${HOST}
        ...
```
