### ISSUE TITLE
Recipe in Recipe Syntax

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#191]
Allow recipe within a recipe to contain a YAML defined recipe.

This is already possible, but flags as being an error using the Schema.

```yml
write:
  - recipe:
        read:
           - connector:
        ...
```
