### ISSUE TITLE
Allow recipe parameters for single row custom functions

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#193]
```py
def my_function(input_column, parameter)
   # do something...
```

```yml
wrangles:
  - custom.my_function:
      parameter: value  # allow this
      output: column
```
