### ISSUE TITLE
select.dictionary_element Needs first_element option

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#194]
We commonly generate dictionary elements using custom extracts and use_labels.  So when you go to extrract a specific elemnent, it currently requires 2 wrangles, first to get the elemenbt and second to select the first element from the list.  This option would help with Recipe conciseness.

**Comment by ChrisWRWX** [comment]
Strongly against this as proposed. Adding too much functionality to wrangles makes them significantly more confusing when that functionality strays away from their stated purpose. I don't think brevity is worth making the behaviour of an individual wrangle opaque.

I think investigating ways to wrap a series of wrangles into a repeatable step is a good idea, to make these repeated steps more concise.

For this specific instance, I'd propose adding a select.element wrangle that works more generally. Perhaps we can derive ideas from python syntax, something like:

```yml
wrangles:
  - select.element:
      input: column[0]['key']     # python syntax here for list/dict elements
      output: new column
      default: 'absent' # allow a default value if not found
```
