### ISSUE TITLE
Log a selected range of data

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#197]
Currently, the log will log all of the column/s

Maybe have a way to log only the first 10 or give a range 10 to 20 rows

```yaml
- log:
    row: 13   # or 13:26 similar to python slicing
    columns:
      - muCol
     
```
