### ISSUE TITLE
Add a run option for Postgres

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#227]
As for MSSQL.

```yml
run:
  on_start:
    - postgres:
         host: 
         user: 
         password: 
         command: |
              SQL instruction
```
