### ISSUE TITLE
New Wrangle: SQL

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#23]
Apply a SQL statement to the current state of the recipe.

e.g.

```yaml
wrangles:
  - sql:
      command: |
         SELECT *
         FROM df
         WHERE column > 5
```
