### ISSUE TITLE
Where for Read

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#241]
Add where for read

This is generally suboptimal and refining the data from the source is better but sometimes that's not possible, so it would be nice to offer this option.

e.g.

```yml
read:
  - file:
      name: file.xlsx
      where: category = 'something'
```
