### ISSUE TITLE
Split.dictionary allow setting default key/values

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#246]
Allow setting defaults if the input dictionary does not contain a value, to ensure certain columns are always created.

```yml
wrangles:
  - split.dictionary:
      input: Results
      default:
         Key1: Val1
         Key2: Val2
```
