### ISSUE TITLE
Merge Lists Single/Double Quote Conflict

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#274]
When merging two lists of strings, if one uses single quotes and the other uses double quotes the merge carries over the brackets from the single quote list.

```yaml
wrangles:
  - extract.custom:
      input: Description
      output: Brands Extracted

  - merge.lists:
      input:
        - Manufacturer
        - Brands Extracted
      output: All Brands
```

Where Manufacturer is a column in the dataframe containing a string, All Brands ends up as:
["Dayton-Grainger", "['Dayton-Phoenix ']"]

**Comment by thomasstvr** [comment]
Having trouble duplicating this. Currently tried:

| Stuff | Things |
|:-----:|:--------:|
| Grainger's | 2" |
| Dayton's | 3" |

->

| Stuff | Things | Measurements | Combined |
|:-----:|:--------:|:----------------:|:------------:|
| Grainger's | 2" | ['2"'] | ["Grainger's", "2\""] |
| Dayton's | 3" | ['3"'] | ["Dayton's", "3\""] |

```yaml
  - extract.custom:
      input: Things
      output: Measurements
      model_id: xxxxxxxx-xxxx-xxxx

  - merge.lists:
      input:
        - Stuff
        - Measurements
      output: Combined
```
