### ISSUE TITLE
Python Wrangle

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#278]
Add a wrangle to evaluate simple python code for string or object manipulation.

**Comment by ChrisWRWX** [comment]
e.g.

```yml
wrangles:
  - python:
      command: header1 + " " + header2
      output: result
```

```yml
wrangles:
  - python:
      command: |
        [
          x + " " + y
          for x, y
          in zip(header1, header2)
        ]
      output: result
```
