### ISSUE TITLE
Convert Length - not working from Ft to Metre

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#282]
Need to convert length but not working.  I've shared a recipe with you call Convert Length.  Can you pls debug on data I attached to email just now?

**Comment by ChrisWRWX** [comment]
So... it only works currently with 'span' output.

```yml
# 20 ft -> ["6.10m"]
wrangles:
  - extract.attributes:
      input: ${selection}
      output: ${selection}
      desired_unit: metre
      attribute_type: length
```

You could double extract to convert and then get an object if you need an object. Not elegant, but works.


```yml
# 20 ft -> [{"symbol": "m", "unit": "metre", "value": 6.1}]
wrangles:
  - extract.attributes:
      input: ${selection}
      output: ${selection}
      desired_unit: metre
      attribute_type: length

  - select.element:
      input: ${selection}[0]

  - extract.attributes:
      input: ${selection}
      output: ${selection}
      attribute_type: length
      responseContent: object
```
