### ISSUE TITLE
merge.lists -> add param for include_empty

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#293]
Add the same setting as we already have for merge.to_list. Default it to false (i.e. do not inclued empty items)

**Comment by thomasstvr** [comment]
I might be missing something here, but what would include_empty do for merge.lists? If the list is empty, then including it would do nothing to the final output.

**Comment by ebhills** [comment]
Need arises when 1 or the input 'lists' is actually just strings. In this case, you get an unwanted "" for rows that are empty. sorry - should have included the specific example (see row 1) to begin with:
```
wrangles:
  - convert.from_json:
      input: List 2

  - merge.lists:
     input:
       - List *
     output: Merged
     # want include_empty here

```



List 1 | List 2 |  Merged
-- |  -- | --
  | ["item 1", "item 2"] | [**""**,"item 1","item 2"]
ksjdf | ["item 1", "item 2"] | ["ksjdf","item 1","item 2"]
ksjf | ["item 1", "item 2"] | [["ksjf","item 1","item 2"]
kj | ["item 1", "item 2"] |  ["kj","item 1","item 2"]



</body>

</html>
