### ISSUE TITLE
Allow for wrangles output to be a standardize of the input

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#297]
While working on making the Akeneo connector better, I come across this idea of having the output of a wrangle be the standardization of the input as an option. In the case of Akeneo, removing all spaces and replacing them with "_" and removing periods, commas and other not allowed characters

I did this using custom functions:
```yaml
wrangles:
  - custom.akeneo_stuff:
      input: 
        - col 1
        - col 2
     output: 
        standardize: "model_id" #-> the output will be a list => [col1, col2]
```

This would look something like this in python:

```python
    if isinstance(output, dict):
        output = _wrangles.standardize(input, model_id=list(output.values())[0])
        # maybe have other wrangles based on the key -> classify, extract
```

**Comment by ChrisWRWX** [comment]
Maybe not 100% what you had in mind, but I've added a PR with the ability to use wrangles as part of rename. That seems to achieve a similar effect + with many more capabilities than just standardize.

```yml
  wrangles:
    - rename:
        wrangles:
          - convert.case:
              input: columns
              case: upper
```
