### ISSUE TITLE
Split.text gives "When using a filter in Wrangles.... use 'output: sheet'...." error

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#304]
When running the following recipe:

```yaml
wrangles:
  - split.text:
      input: LongText
      output: Output*
      char: ':'
```

Only 100 rows are output (even though whole column is selected) and the error warning "
When using a filter in Wrangles, be sure to use 'output: sheet' in recipe" is shown.
