### ISSUE TITLE
Split Dictionary Lists/Wildcard

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#305]
Need to allow split.dictionary to take in a list of inputs as well as a wildcard. Allow option for overriding a column (common key in the dictionaries being split) with precedence to the first/last/whatever order.

```yaml
wrangles:
  - split.dictionary:
      input: something *
```
| somethine 1 | something 2 |
|:--------------:|:--------------:|
| {"a": 1, "b": 2, "c": 4} | {"c", 3} |  

-> 

| a | b | c |
|:-:|:--:|:--:|
| 1 | 2 | 4 |
