### ISSUE TITLE
Group By - add option to aggregate as a list

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#307]
```yml
wrangles:
   - select.group_by:
       by: agg
       list: to_list
```
