### ISSUE TITLE
Add native head and tail recipe wrangles

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#310]
```yml
wrangles:
  - select.head:
       n: 10

  - select.tail:
       n: 10
```
