### ISSUE TITLE
Significant Figures

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#319]
Just as with Wrangles XL, create a significant figures wrangle in Wrangles PY.

**Comment by cerdamario13** [comment]
Here is the sigFigs function. It works with strings and numbers(float, int) in input

```yaml
 wrangles:
  - format.sigFigs:
       input: col1
       output: out1
       sigFigs: 3 -> default is 3
```

| col1                 | out1              |
|:---------------------|:------------------|
| 13.45644 ft          | 13.5 ft           |
| length: 34453.3323ft | length: 34500.0ft |
| 34.234234            | 34.2              |
| nothing here         | nothing here      |
| 13.4565              | 13.5              |
| 1132424              | 1130000.0         |
|                      |                   |
