### ISSUE TITLE
MSSQL Connector / Run - allow a list of commands

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#32]
Allow a list of commands as well as a single command for the run function of the MSSQL connector.

e.g.

```yaml
run:
  on_start:
    - mssql:
        host: 
        user: 
        password: 
        command:
          - EXEC [StoredProcedure1]
          - EXEC [StoredProdedure2]
```
