### ISSUE TITLE
split.text Inclusive and Cleanup

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#333]
Currently works if char is input as a list (since this causes it to hit _re.split() instead of simply .split()) and is wrapped in parenthesis (regex capture group). Would be nice to have this as a toggle or something much simpler to pass/write in a recipe.

```yaml
wrangles:
  - split.text:
      input: gauge
      output: 
        - Thickness
        - Thickness UOM
        - Trash
      char: 
        - (ga|micron)
```

| gauge |
|:-------:|
| 100ga |
| 80ga |
| 50micron |

=>

| gauge | Thickness | Thickness UOM | Trash |
|:-------:|:-----------:|:-----------------:|:------:|
| 100ga | 100 | ga | |
| 80ga | 80 | ga | |
| 50micron | 50 | micron | |

Would need to handle empty strings being returned from the split and causing issues with columns being returned without wildcard.
