### ISSUE TITLE
Add wildcard/regex option for rename

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#334]
```yml
wrangles:
  - rename:
      input: "*.list"
      output: "*"
```

or

```yml
wrangles:
  - rename:
      input: "regex: (.*).list"
      output: \1
```
