### ISSUE TITLE
Capture Column Does Not Exist in Write, Still Produce Output

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#339]
Currently when you get to Write and specify a Column that doesn't exist, you get no output.  When playing with what's in and out, this is a common, and frustrating error. Can we catch it, and then include the column with the error message for it's value?

**Comment by ChrisWRWX** [comment]
Not sure I understand this request. When you try to write a column that doesn't exist, the existing behaviour is an error stating the column doesn't exist. Are you suggesting we should make a new column with an error message instead?

**Comment by ChrisWRWX** [comment]
Pending publishing the next version, added the ability to indicate columns are optional. Indicated with a ?

This works broadly - for input on wrangles, columns or not_columns on read and write. It may still error depending on what happens downstream of this code, if that column missing now causes something not to be possible to execute.

```yml
# Will fail if header1 or header2 are not present
# but will not fail if header3 is missing
write:
  - file:
       name: example.xlsx
       columns:
         - header1
         - header2
         - header3?
```
