### ISSUE TITLE
Recursive recipes

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#34]
Allow a recipe to be the source of a recipe.

e.g.

```yaml
read:
  - union:
      sources:
        - recipe:
             name: recipe1.wrgl.yml
             variables:
                var1: val1
        - recipe:
             name: recipe2.wrgl.yml
```
