### ISSUE TITLE
Recipe Schema: recipe wrangle is broken

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#345]
Not getting suggestions for this:

```yml
wrangles:
  - recipe:
      # etc.
```
