### ISSUE TITLE
More Powerful tokenize Wrangle

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#357]
Current tokenize wrangle essentially just splits on spaces. This is inadequate when doing things like compare and remove.  An idea: maybe we put a wrangles interface on an opensource tokenizer. For example, NLTK has a [full package](https://www.nltk.org/api/nltk.tokenize) dedicated to tokenizing, and a [specific module](https://www.nltk.org/api/nltk.tokenize.regexp.html) that leverages regex.

**Comment by ChrisWRWX** [comment]
Added a parameter called method. The default is as before to split on spaces. There's also a couple of regex based word-boundary ones.

Also an option to set regex:<a pattern> to use a custom regex pattern.

```yml
wrangles:
# Using spaces, as before and default
# if not specified
- split.tokenize:
     input: column
     method: space

# Using regex word boundaries
- split.tokenize:
     input: column
     method: boundary

# Using regex word boundaries
# but dropping spaces
- split.tokenize:
     input: column
     method: boundary_ignore_space

# Using a custom regex pattern
- split.tokenize:
     input: column
     method: regex:[abc]
```

I haven't investigated any third party libraries, but added the ability to use custom functions, so they're easy to incorporate now. If we find a good one, we can potentially incorporate it as one of the default methods. Depending on the exact implementation of the third party tokenizer, assuming it's just single string in -> list out, it should be possible to just pass that directly as the custom function.

```yml
wrangles:
# Using a custom function
- split.tokenize:
     input: column
     method: custom.tokenizer
```

```py
def tokenizer(value):
    # will be executed once per string
    # return split value
```
