### ISSUE TITLE
Wrangling Multiple Columns with 1 Wrangle

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#359]
the **rename** Wrgl is a favorite because of the ability to do multiple pairs with one call. Can we do that with other wrangles? For example:
``` 
split.tokenize:
      input: DistrE Article
      output: DistrE Article tokens
split.tokenize:
      input: next Colm
      output: next Colm tokens
```
Could it be called for multiple at once like:
``` 
split.tokenize:
      DistrE Article: DistrE Article tokens
      next Colm: next Colm tokens
```
This would be a big improvement in terms of succintness. And maybe it makes the there and back more efficient too?

**Comment by ChrisWRWX** [comment]
This is complicated because it overlaps with the params and can potentially be ambiguous whether something is a parameter or a column. Input also has a lot of code to deal with special cases such as wildcards, also optional columns now. Further, it's not always consistent the number of input to output columns so a dictionary approach doesn't always work. I don't think this will work universally.

I also don't like the idea of splitting the approach, I'd rather we used a consistent in/out for people to become familiar with. I'm more for implementing this as an exception for certain wrangles that commonly have long lists. We already have an issue for copy #336 

Note that for many wrangles you can already do (although this does depend on the exact behaviour of the wrangle):

```yml
wrangle:
  input:
    - col1
    - col2
  output:
    - out1
    - out2
```
