### ISSUE TITLE
Divide notifications into specific actions

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#36]
At the moment we have 

```yaml
run:
  on_start:
    - notification:
        url: apprise://url
        title: title
        body: body
```

Also split off specific ones

```yaml
run:
  on_start:
    - notification:
        ...

    - notification.telegram:
        ...

    - notification.slack:
        ...
```
