### ISSUE TITLE
Where Param Converts Integer to String

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#369]
When using where, say for math, the data for the filtered column is converted to a string.

**Comment by ChrisWRWX** [comment]
Are you sure about this? I'm not able to reproduce this with a minimal example. Can you create a reproduceable example?

If you inspect the resulting dataframe from this, header1 and header2 are both still integers.
```
read:
  - test:
      rows: 5
      values:
        header1: 1

wrangles:
  - copy:
      input: header1
      output: header2
      where: header1 = 1
```

**Comment by ChrisWRWX** [comment]
Interestingly, this actually makes it a float:
Still a number at least, but would be better if it preserved the data type

```yml
read:
  - test:
      rows: 100
      values:
        header1: <int>

wrangles:
  - copy:
      input: header1
      output: header2
      where: header1 > 50
```

**Comment by thomasstvr** [comment]
Yes, I recreated like so:

```yaml
wrangles:
  - math:
      input: (Column2 - Column1)/Column1
      output: Column3
      where: NULLIF(Column1, '') IS NOT NULL
```

```python
data = pd.DataFrame({
    'Column1': [65, 72, '', 92, 87, 79],
    'Column2': [2, 5, 4, 2, 1, 6]
})
```

If you put a break point on math, you can see that the column that was filtered on is now made up of strings.
