### ISSUE TITLE
Notification - Slack

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#37]
Add a specific notification for slack

e.g.
```yaml
run:
  on_start:
    - notification.slack:
        required: parameters
```
