### ISSUE TITLE
Make native version of pandas.map

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#382]
```yaml
  - pandas.map:
      input: Whse Status
      output: Whse Status
      parameters:
        arg:
            S: S
            O: O
            X: CALL
            M: CALL
```

**Comment by thomasstvr** [comment]
Currently working on Transform branch. The one thing I can't figure out is how to pass functions through. 

See the .format example here:
https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html#examples

**Comment by thomasstvr** [comment]
Now called "lookup," the wrangle will allow users to lookup up values based on the key(s) they specify. Users can reference stored data with a model id, and return all columns/values associated with their key or only the columns they dictate. Values can also be overridden as well.

Simple, one to one lookup example:
```yaml
wrangles:
  - lookup:
      input: Col1
      output: desc
      model_id: 5555-5555-55555555
      reference: desc
      default: Default description
```
The above would lookup the values from Col1 in the key column of the wrangle with that model_id, and return the corresponding value from the desc column. Default fills in values where keys were not found.

return all columns as a dictionary:
```yaml
wrangles:
  - lookup:
      input: Col1
      output: Output Dict # A new column name 
      model_id: 5555-5555-55555555
```

Return selected columns:
```yaml
wrangles:
  - lookup:
      input: Col1
      output: 
        - desc
        - brand
      model_id: 5555-5555-55555555
      reference:
        - desc
        - brand
      default: Default description
```

Return selected columns while overriding key values:
```yaml
wrangles:
  - lookup:
      input: Col1
      output: 
        - desc
        - brand
      model_id: 5555-5555-55555555
      reference_columns:
        - desc
        - brand
      reference:
        part_no1:
          desc: override the current
          brand: override the current
        part_no2:
          desc: override
```
Returns desc and brand, but overrides both values for part_no1 and overrides only desc for part_no2.
