### ISSUE TITLE
Extract.AI assume array items should be strings

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#390]
Assume items/string for type array if not specified

```yml
column:
    type: array
    # Inject below if not specified
    items:
      type: string
```
