### ISSUE TITLE
split.dictionary - add prefix/suffix

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#406]
Add an optional prefix and/or suffix to split columns.

Allow as string or array. Must equal 1 (applied to all) or match length of input (applied to respective input).

```yml
wrangles:
  - split.dictionary:
        input: a column
        suffix: _abc
```

```yml
wrangles:
  - split.dictionary:
        input:
          - column1
          - column2
        suffix:
          - _col1
          - _col2
```

**Comment by ChrisWRWX** [comment]
Using this a trial for a more generic approach/mechanism for dynamically selecting/renaming outputs.

```yml
wrangles:
  # Choose columns to output by name, with a wildcard,
  # or matching a regex pattern
  - split.dictionary:
      input: column_containing_dicts
      output:
        - a_column
        - column*
        - "regex: column_[a-z]"

  # Add a suffix to all output columns
  - split.dictionary:
      input: column_containing_dicts
      output:
        - "*": "*_SUFFIX"

  # rename column1, but leave all others unchanged
  - split.dictionary:
       intput: column_containing_dicts
       output:
          - column1: renamed1
          - "*"
```
