### ISSUE TITLE
Create.column - use test placeholder values

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#43]
Allow create.column to also use the placeholder values that generate random data from the test connector.

e.g.
```yaml
wrangles:
  - create.column:
      output: column name
      value: <sentence>
```
