### ISSUE TITLE
Ignore Case for Split.text

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#430]
Would be nice to have an ignore_case parameter for split.text.

**Comment by ChrisWRWX** [comment]
Seems like the way to go for this is via regex, and we already have a regex option, so this can be achieved like so:

```yml
# ['1x2', "1X2"] -> [["1","2"], ["1","2"]]
wrangles:
  - split.text:
      input: col1
      char: 'regex:(?i)x'
```

I've added this as an example in the docs.
