### ISSUE TITLE
select.element -> allow for native python list syntax

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#431]
Allow the user to use list slicing

```yaml
wrangles:
  - select.element:
      input: col[1:-1]
      output: out
```

```yaml
wrangles:
  - select.element:
      input: col[:4]
      output: out
```
