### ISSUE TITLE
Select.dictionary_element fails if the input isn't a dictionary

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#44]
If any of the rows don't contain a dictionary, select.dictionary_element fails with an error.

```yaml
wrangles:
  - select.dictionary_element:
      # This fails if any of the rows aren't a dictionary.
       
```

Have it return nothing instead for rows that fail.
