### ISSUE TITLE
split.text wrangle fails if a string is passed without ":"

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#443]
If element is passed as a string, the wrangle fails with an out of index error
```yaml
wrangles:
  - split.text:
      input: other
      output: split
      char: " "
      element: "1" -> string passed
```

![image](https://github.com/wrangleworks/WranglesPY/assets/43070036/c25b8727-8f98-44f2-859e-4f8e98b844fd)

But it works if the string contains a range -> element: "1:3"
This could also explain why a recipe from Excel fails with a string

possible solution to add list slicing

```python
 elif isinstance(element, str):
        if (':' not in element):
          df[output] = df[output].apply(lambda x: x[int(element)])
        elif (element[0] == ':'):
          slice_values = int(element.split(':')[-1])
          df[output] = df[output].apply(lambda x: x[:slice_values])
        elif (element[-1] == ':'):
          slice_values = int(element.split(':')[0])
          df[output] = df[output].apply(lambda x: x[slice_values:])
        else:
          slice_values = [int(x) for x in element.split(':')]
          df[output] = df[output].apply(lambda x: x[slice_values[0]:slice_values[1]])

```
