### ISSUE TITLE
Add accordion

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#450]
Add an accordion wrangle that will execute a series of wrangles against cells containing lists and return a list.

e.g.
```yml
  read:
    - test:
        rows: 5
        values:
          list_column:
            - a
            - b
            - c

  wrangles:
    - accordion:
        input: list_column
        wrangles:
          - convert.case:
              input: list_column
              case: upper
```
