### ISSUE TITLE
Create Embeddings Wrangle: change default output_type to numpy array

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#462]
Curreently output_type default is python list.  But why would someone want that format? The main (only) reason someone will create embeddings is for similarity or some other sematnic task, which requires the numpy array, right?

**Comment by ChrisWRWX** [comment]
It's broadly just a mirror of the OpenAI implementation, which also produces a python list by default. I agree with that though, and wouldn't be for changing it.

As a native python object, it's much more universally supported. If you write the data out somewhere, save it to a file, manipulate it using other code/wrangles etc., those are much more likely to work. Numpy arrays won't work with many file types and won't translate to JSON easily without additional code. They're a lot more likely to have cryptic issues if you don't know what you're dealing with. I feel that opting in to the less familiar data type is sensible.

Similarity should work with either, and I'd expect any additional wrangles we introduce to likewise work with either. It's more efficient with a numpy array, but for small data sets that difference is likely negligible.

**Comment by ebhills** [comment]
then let's at least give a error that helps use sort it out. I spent 30 mins...  And put it in the wrangles.io  doc that similarity needs

**Comment by ChrisWRWX** [comment]
It doesn't need a numpy array - it works with either. Please will you share the recipe and context (wranglesPy? - if so version, wranglesXL?) that wasn't working as expected - I am not able to reproduce your issue.

This works with both numpy array and python list, with each of the 3 similarity methods for me.
Running from Excel - writing out only the score because neither format currently will write to Excel.
```
read:
  - test:
      rows: 5
      values:
        header1: value1
        header2: value2

wrangles:
  - create.embeddings:
      input:
        - header1
        - header2
      api_key: ${OPENAI_API_KEY}
      # output_type: numpy array
        
  - similarity:
      input:
        - header1
        - header2
      output: score
      method: adjusted cosine

write:
  - dataframe:
      columns:
        - score
```
