### ISSUE TITLE
Wrangles.Split.Text - Fails on column number mismatch.

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#47]
The below fails if the number of output columns doesn't match the number of columns after splitting.

Prevent it from failing and instead have it either:

- Leave the extra columns empty if there are more than needed.
- Discard the extra data if there are fewer than after spliting (e.g. 2 columns given, but 4 split columns - then include the first 2 results)

```yaml
wrangles:
  - split.text:
      input: Column
      output:
         - Output1
         - Output2
```
