### ISSUE TITLE
Regex Special Characters in Wild Card Definitions

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#488]
```yaml
wrangles:
  - split.dictionary:
      input: col1
      output: .*2
```

| col1 |
|:-----:|
| {key1: value1, key2: value2} |
| {key1: value3, key2: value4} |

->

| .ey2 |
|:-----:|
| value2 |
| value4 |
