### ISSUE TITLE
Select.dictionary_element element Must Be a List For Wildcard and Regex

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#489]
When using a wildcard or regex, the element must be a list in order to work. Does not work when passed as a string.

```yaml
  - select.dictionary_element:
      input: col1
      element: 
        - "regex: .*2"
```
^ Works

```yaml
  - select.dictionary_element:
      input: col1
      element: "regex: .*2"
```
^ Does not work
