### ISSUE TITLE
select.sample - for rows treat appropriate string as a number

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#493]
Allow string equivalent to numbers to work. e.g. '1' == 1

```yml
wrangles:
  - select.sample:
      rows: '10'
```
