### ISSUE TITLE
Add if conditions

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#495]
Allow using an if condition to choose whether to execute parts of a recipe.

e.g.

```yml
write:
  - file:
      name: a.xlsx
      if: ${variable} == 'value'
```
