### ISSUE TITLE
select.keys

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#496]
often need to select keys in a dictionary. Would be good to make it a simple wrangle vs having to use python.

**Comment by ebhills** [comment]
@thomasstvr : did we / you do anything with this? I assume not.

The use case is 2 fold:
  1. Want to get a list of keys for comparison of keys across dictionaries.
  2. Want to split a dictionary into 2 columns: list of keys and a list of values.  This would enable exploding a dictionary of attributes into rows (which is a common PIM representation).

Here is the custom function I created that does this:
```
def split_attributes(df,dict, output):
    df[output[0]] = df[dict].apply(lambda x: list(x.keys()))
    df[output[1]] = df[dict].apply(lambda x: list(x.values()))
    return df
```

My inclination is to add this to split.dictionary: as a new parameter like this:
```
  - split.dictionary:
      input: My Dict
      output: 
        - Keys
        - Values
      mode: to_lists # default is current behavior 
                     # to_columns
```
My Dict | Keys | Values
-- | -- | --
{"a": 123, "b":   "kshdf"} | ["a","b"] | [123,"kshdf"]
{"b": 123, "c":   "kshdf"} | ["b","c"] | [123,"kshdf"]
```

**Comment by thomasstvr** [comment]
@ebhills correct, we did not.

**Comment by ebhills** [comment]
see my previous comment about mode.  think better param name and values are like this:

```yaml
  - split.dictionary:
      input: My Dict
      output_format: columns # current default behavior 
      # output:  if you don't specify keys become colm names


  - split.dictionary:
      input: My Dict
      output_format: two_lists # new behavior 
      output:  # we could add a default behavior here if no output specified then [My Dict keys], [My Dict values]
        - Keys
        - Values
```
