### ISSUE TITLE
Column Name as Key for select.dictionary_element

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#497]
Need ability to pull a specific Key: Value as a function of the value in another column. Let's allow the Key name to be the column name.

**Comment by thomasstvr** [comment]
This can now be done using a matrix or a python wrangle.

matrix:
```
  - matrix:
      variables:
        var: set(My_Column)
      wrangles:
        - select.dictionary_element:
            input: dictionary
            output: output
            element: ${var}
            where: My_Column = '${var}'
```

python:
```
- python:
    command:
      dict_col[key_col]
    output: out_col
```
