### ISSUE TITLE
select.list_element from a string

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#50]
As of now, `select.list_element` only works if the input is a list. If you have a string where you want the first word, you need to convert it to a list, then select the element.

e.g.
- split.text: # split column first
      input: Name
      output: Name
      char: ' '
  
- select.list_element:
    input: Name
    output: Name_first_token
    element: 0

Maybe have it accept strings also. If it is a string would also have to worry about specifying a separator.

Could maybe be done using a regex wrangle, right or substring (but what if the length of character changes?)

**Comment by ChrisWRWX** [comment]
I don't think select.list_element is the right place for acting on strings. It's a little cryptic to include string operations within that.

Perhaps it's better to include an option within split.text to not return all values.


```yaml
wrangles:
  - split.text:
      input: column
      output: new column
      char: ' '
      element: 0                # get a specific element? Return result as a string instead of a list.
      element: '1:2'            # allow python style slice? The colon might cause issues here.
```
