### ISSUE TITLE
where: doesn't work with extract.ai 

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#501]
get an error saying dict is not hashable.  

```yml
- extract.ai:
      input: Color
      # messages: >-
      #   Put additional user messages here.
      output:
        Standard Colors:
          type: array
          # items:
          #   type: object
          description: >-
            List of standard colors.
          examples: # spurious on output sometime being just strings, refined by removing extra spaces and seems to work reliably now
            - ["Brown", "Charcoal", "Granite City Blend", "Westchester Blend"]
            # - [{"PREMIUM": ["Autumn Blend","Oyster"]}, {"DELUXE": ["Pennsylvania Blue"]}]
            # - [{"DELUXE": "Pennsylvania Blue"}]
          default: []
        Premium Colors:
          type: array
          # items:
          #   type: object
          description: >-
            List of PREMIUM colors.
          examples: # spurious on output sometime being just strings, refined by removing extra spaces and seems to work reliably now
            - ["Brown", "Charcoal", "Granite City Blend", "Westchester Blend"]
            # - [{"PREMIUM": ["Autumn Blend","Oyster"]}, {"DELUXE": ["Pennsylvania Blue"]}]
            # - [{"DELUXE": "Pennsylvania Blue"}]
          default: []
        Deluxe Colors:
          type: array
          # items:
          #   type: object
          description: >-
            List of DELUXE colors.
          examples: # spurious on output sometime being just strings, refined by removing extra spaces and seems to work reliably now
            - ["Brown", "Charcoal", "Granite City Blend", "Westchester Blend"]
            # - [{"PREMIUM": ["Autumn Blend","Oyster"]}, {"DELUXE": ["Pennsylvania Blue"]}]
            # - [{"DELUXE": "Pennsylvania Blue"}]
          default: []
      api_key: ${OPENAI_API_KEY}
      model: gpt-4o
```
