### ISSUE TITLE
extract.regex - How do you specify capture groups?

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#502]
Need ability to specify capture groups like \1 \2 etc.  But the output filed is just the column name. Maybe add a param called return?

**Comment by ebhills** [comment]
Also - it need first_element parameter

**Comment by ebhills** [comment]
One exmaple: I want to get the first part of this string but only the part in the ()s.
1-3/8"-16 - >  ```^([^\"]+)\"?-``` 0-> 1-3/8
According to regex101 this should work, but our wrangle includes the ":
```
  - extract.regex:
      input: Diameter Size
      output: Diameter
      find: '^([^\"]+)\"?-' 
```
output -> 1-3/8"
