### ISSUE TITLE
add prefix/suffix to text

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#51]
I have noticed that some data changes are only a prefix/suffix added to the output column. This could be done with `merge.concatenate` only if a prefix column exists, if not, one needs to be created.

e.g. 
- create.column:
      output: initials
      value: 13H
- merge.concatenate:
      input:
        - initials
        - Name
      output: FamilyCode
      char: '-'

possible solution:

- wrangles:
    insert_fix:     # better name of course
      input: Name
      add_value: '13H'
      value_type: prefix

**Comment by cerdamario13** [comment]
Added two wrangles, suffix and prefix

```yaml
wrangles:
  - format.suffix:  # or format.prefix
      input: col
      output: pre_col   # optional
      value: 'prefix-'
```
