### ISSUE TITLE
Accordion creates empty string for empty list

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#524]
```yml
wrangles:
  - convert.from_json:
      input: input

  - accordion:
      input: input
      wrangles:
        - convert.case:
            input: input
            case: upper
```

| input | -> | output |
| :-- | :- | :- |
| [] |  | [""] # error here |
| ["a","b"] |  | ["A","B"] |
