### ISSUE TITLE
Pricing (or any other value) category label wrangle

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#54]
Wrangle that sorts values into ranges (labels) using `pandas.cut()`

Should this be separate from `filter`? 
`filter` reduces size of dataFrame, this will keep the same size always.

Data sample:

|   cost | category        |
|-------:|:----------------|
|    200 | under $250      |
|    503 | $500-$1,000     |
|    800 | $500-$1,000     |
|   1300 | $1,000-$2,000   |
|   2500 | $2,000-$3,000   |
|   3013 | $3000 and above |

possible wrangle:

```yaml
wrangles:
 - value_category:
     input: cost
     output: category
      values:   
         - 200
         - 250
         - and so on... # could import as variables, keep recipe short
       labels:
         - 'under $250
         - '$250-$500
         - and so on # could import as variables, keep recipe short
```

code:

```python
data['category'] = pd.cut(
    x=data['cost'],
    bins=[0, 250, 500, 1000, 2000, 3000, math.inf],
     labels = [
        'under $250',
        '$250-$500',
        '$500-$1,000',
        '$1,000-$2,000',
        '$2,000-$3,000',
        '$3000 and above'
    ]
)
```

**Comment by ChrisWRWX** [comment]
Seems like a good addition. I'd prioritise this one.

- Yes, I'd consider this different from filter.
- I'd name it **create.bins** - I think binning is the most widely recognised term for this.
- Test the behaviour of the outer bounds. They won't be able to add infinity in the yaml, so perhaps automatically add +/- infinity at either end if that is needed/works well.
- Allow an integer or list for the bins. The interval index looks like it needs to pass in a separate data structure, so wouldn't work naturally. I'm struggling to think when that would be usefully beyond the simple list though, so maybe just skip that.

```yaml
wrangles:
  - create.bins:
      input: cost
      output: cost bins
      bins:   
        - 200
        - 250
        - and so on... # could import as variables, keep recipe short
      labels:
        - under $250
        - $250-$500
        - and so on # could import as variables, keep recipe short
```

**Comment by cerdamario13** [comment]
When passing values as variables (from python variables to recipe ${variable}) the list must be converted to a string, otherwise an error occurs (typeError)

In recipe, when using " " around the ${variable} notation, an error occurs 
`Exception has occurred: ValueError
could not convert string to float: "['-', 250, 500, 1000, 2000, 3000, '+']"`


below is the combination that works

python

```python
bin_labels = [
    'under $250',
    '$250-$500',
     and so on...
]

bin_values = [
    '-',
    250,
    and so on...
]

variables = {
    # Pricing Categories, must be strings
    'bin_values': str(bin_values),
    'bin_labels': str(bin_labels),
}
```
Yaml
```yaml
- create.bins:
      input: IMAP_Value
      output: Pricing
      bins: ${bin_values}  # cannot be surrounded by ""
      labels: ${bin_labels}
```
