### ISSUE TITLE
Recipe Connector

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPy#56]
Allow this to pull the recipe from other sources. Web url? Git repository?

e.g.

```yaml
read:
  - recipe:
       name: https://host.com/recipe.wrgl.yml
```
