### ISSUE TITLE
Remove Words Capitalization

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#57]
Look at Remove_words and see if it can
- preserve case
- inputs as raw (no case conversion)

**Comment by cerdamario13** [comment]
Also look into what happens when a list to remove is empty

**Comment by cerdamario13** [comment]
Fixed the error out of range
The issue was not tokenizing correctly if using `tokenize_to_remove`
`[tokenize(to_remove[x]) for x in range(len(to_remove))]`

**Comment by cerdamario13** [comment]
@ebhills 

Fixed out of range index (see above comment) error.
Added `ignore_case` as a parameter. If set to False, the input and to_remove will be taken as Raw tokens.

```yaml
- remove_words:
      input: Column1
      to_remove:
        - materials
        - Case Colours
      output: Item
      tokenize_to_remove: True
      ignore_case: True
```
