### ISSUE TITLE
Allow using custom functions for select.group_by

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#570]
```yml
wrangles:
  - select.group_by:
      by: column
      custom.fn: other_column
```
