### ISSUE TITLE
On Demand Standardize

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#58]
Add a runtime ability to standardize. Equivalent to standardize regex function, but define the in/out within the recipe instead rather than having to create a Wrangle for a single transformation.

This might fit into the standardize code as an alternative to providing a model id rather than having to create something new.

```yaml
wrangles:
  - standardize:
       input: column
       output: new column
       find: a pattern
       replace: output pattern
```

**Comment by cerdamario13** [comment]
On demand standardize working

```yaml
wrangles:
  - standardize:
      input: col
      find: '\d+'
      replace: 'number_here'
```
