### ISSUE TITLE
Get List and Assign Multiple Elements using Python Wrangle

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#601]
I am breaking apart a Class Path that uses | as the separator. 
  - Cutting Tools and Metalworking|Tooling Components|Workholding Fasteners|Workholding Flange Nuts

I thought I could use the following:
```
  - python:
      output: 
          - Category
          - Group
      command: "Product_Path.split('|')[-2]"
```
Since the split should return a list with the last 2 elements.  But that only gives me the Group.

So as is I have to run the split twice
```
  - python:
      output: Category
      command: "Product_Path.split('|')[-1]"
  - python:
      output: Group
      command: "Product_Path.split('|')[-2]"
```

**Comment by ChrisWRWX** [comment]
Your syntax is just incorrect.

[-2] gets the second last element from the list, so there's only one value.

You need [-2:]

```yml
wrangles:
  - python:
      output: 
          - Category
          - Group
      command: "Product_Path.split('|')[-2:]"
```
