### ISSUE TITLE
Split.list Wildcard Breaks When Passed as a List

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#608]
When using a wildcard and passing the output column as a list there is a value error that is thrown:

"Exception has occurred: ValueError
split.list - Columns must be same length as key"

```yaml
  - split.list:
      input: column
      output: 
        - Col*
```
