### ISSUE TITLE
select.group_by splits column name if no aggregation is used

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#609]
Column name is split with periods if only by is used.

```yml
wrangles:
  - select.group_by:
      by: to_group
```

-->

|  t.o._.g.r.o.u.p | 
| :--: |
|  ... |
