### ISSUE TITLE
SMS Notifications

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPy#61]
Try to find a free SMS service and put to use in notifications.

**Comment by ChrisWRWX** [comment]
This is the library that we're using.

https://github.com/caronc/apprise

Recipe element looks like this:

```yaml
run:
  on_failure:
    - notification:
         url: <this is the apprise url as dictated by their docs>
         title: title of the message
         body:  body of the message
```
