### ISSUE TITLE
Add Wrangle Compare Lists

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#614]
Extend compare wrangles by adding compare lists wrangle

something like this
```yaml
wrangles:
  - compare.list:
      input: 
        - list1
        - list2
      output: Compare
      method: intersection # or difference or overlap?
```

To get started, I think intersection and difference should be straight forward
For nested lists, leave it be. For now the user can flatten the list before the wrangle.

Use only two lists as the input like in `compare.text` then discuss if we want to add more

I can't think of a way to do overlap or if it makes sense...

`compare.text` info for reference
https://wrangles.io/python/recipes/wrangles/compare
