### ISSUE TITLE
Matrix and if do not work together

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#619]
Due to the delayed interpolation of variables by if, and matrix overwriting the original variables, matrix with an if does not work.

Below example should produce 1 sheet depending on the variable switch, but does not.

```yml
read:
- test:
    rows: 5
    values:
        header: value

write:
- matrix:
    variables:
      value: [a]
    write:
        - memory:
            if: ${switch} == '1'
            id: test_matrix_write_if_${value}1
        - memory:
            if: ${switch} == '2'
            id: test_matrix_write_if_${value}1
```

**Comment by ChrisWRWX** [comment]
Reviewed this. The issue is because the newly defined variables replace the existing variables within the scope of the matrix. Most variables are interpreted when the recipe is read at the start, but if specifically delays the interpretation of the variables until it is executed so they can be safely parameterized.

Need to figure out how to address this, but as a workaround, the variable can be explicitly passed by including it within the matrix' variables.

```yml
write:
- matrix:
    variables:
      value: [a]
      switch: ${switch}   # redefine variable
    write:
        - memory:
            if: ${switch} == '1'
            id: test_matrix_write_if_${value}1
        - memory:
            if: ${switch} == '2'
            id: test_matrix_write_if_${value}1
```
