### ISSUE TITLE
Add create.hash

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#630]
Add a wrangle to create a hash from an input.

**Comment by ChrisWRWX** [comment]
```yml
wrangles:
  - create.hash:
        input: <a column>
        output: <a new column>
        method: MD5 or SHA256
```

```py
hashlib.sha256(str(<the input>).encode("utf-8")).hexdigest()
```
