### ISSUE TITLE
Convert.case Sentence Not Working

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#632]
```
wrangles:
  - convert.case:
      input: Column
      output: Other Column
      case: sentence
```

| Column | Other Column |
|:---------:|:----------------:|
| this is a sentence. so is this. this is also a sentence. yet another sentence here as well. |  This is a sentence. so is this. this is also a sentence. yet another sentence here as well. |
