### ISSUE TITLE
Add a spread/unpack operator for columns output

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPY#638]
When writing to a file, if I have a variable that is a list of columns, I would like the ability to also add other columns.
`input_column = [my_element1, my_element2]`

```yaml
wrangles:
  - file:
      name: output.xlsx
      columns:
        - ${input_columns} # This should be unpacked into individual list elements in columns
        - additional_col
```

This will be the equivalent to this

```yaml
wrangles:
  - file:
      name: output.xlsx
      columns:
        - my_element1
        - my_element2
        - additional_col
```
