### ISSUE TITLE
Replace Wrangle Turns Lists Into Strings

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#639]
When running the replace wrangle on a list of strings, the list is converted to a string.

```
  - replace:
      input:
        - Features
      find: "N/A"
      replace: ""
```

This occurs without any errors making it difficult to find and debug. Possibly raise and error when running on anything other than a string or have a silent failure that does not affect the format of the input.
