### ISSUE TITLE
No Error: wrangle in read section of recipe

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#64]
I placed a wrangle in the read section of the recipe by accident. 
There is no error (the error comes later but it is related to key error).
Provide a meaningful error?

e.g.
```yaml
read:
  - file:
      name: <file_name>
      
  - extract.custom:
      input: Name
      output: Tokens
      model_id: <model_here>
```

Maybe have a list of connectors to check (including custom functions) if the input is not in list then raise an error.
