### ISSUE TITLE
Add formatting options for Excel to file connector

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPY#649]
Assuming we are not able to manipulate the file directly with the available options from pandas as seems to be the case.

1. Need to intercept the file and write to memory rather than disk. See 'You can store Excel file in RAM:' here
  https://pandas.pydata.org/docs/reference/api/pandas.ExcelWriter.html#pandas.ExcelWriter

1. Reopen file from memory using openpyxl to be able to manipulate.

1. Add variable to store new format definition

  ```py
  def write(..., format: {}, **kwargs) -> None:
  ```

4. Pass format definition. Start with column definitions. Plan to use wildcard_expansion logic to support setting columns dynamically.
```yaml
write:
  - file:
      name:
      format:
        ...
        columns:
          "column*":
            font_size:
            width: 
          column1:
```

**Comment by ChrisWRWX** [comment]
This issue is intended to keep track of ideas for types of formatting, how to implement, and how to pass them from a recipe. Please feel free to edit this instead of commenting if you want to add a possibility to the list.

See [here](https://docs.google.com/spreadsheets/d/1iGvxkSTihk4Y_d316INdBzOxB9pWMgBeKTxMtUdCR0s/edit?gid=0#gid=0) for a list of functions.

Current ideas on how to pass from a recipe:
```yaml
write:
  # Basic with a default and columns listed individually
  - file:
      name: tests/temp/write_data.xlsx
      format:
        header_height: 62 # Other options for headers?
        column_width: 40
        row_height: 50
        bold: true
        italic: true
        underline: double
        font: Centaur
        font_size: 14
        font_color: blue 
        fill_color: '#0548fb' # Can also use certain colors by name, to be looked up in a dictionary
        alignment:
          horizontal: right
          vertical: bottom
          wrap_text: true
        col*:
          column_width: 10
          header:
            fill_color: red
            font_size: 14
          fill_color: yellow
          font_size: 18
          font: Algerian
        Not Col:
          width: 18
          header_fill_color: '#ff35fb05'
          font_size: 22
          font: Arial
          border:
            color: '#ffd9fb05'
            style: dashed # Should we allow styles?
            left: true
            right: true


  # Using an external dictionary
  - file:
      name: tests/temp/write_data.xlsx
      format: ${Saved_Format_Dictionary}

  # Column index based formatting
  - file:
      name: tests/temp/write_data.xlsx
      format:
        "index-1:5":
          width: 18
          header_fill_color: '#ff35fb05'
          font_size: 22
          font: Arial
          border:
            color: '#ffd9fb05'
            style: dashed # Should we allow styles?
            left: true
            right: true

  # Conditional formatting using some sort of where
  # Defaults are set as usual
  - file:
      name: tests/temp/write_data.xlsx
      format:
        font: Centaur
        font_size: 14
        font_color: blue 
        fill_color: '#0548fb' # Can also use certain colors by name, to be looked up in a dictionary
        conditional:
          where: 
            - Category: 
                equals: Hand Tools
                format:
                  fill_color: '#ff35fb05'
                  font_size: 22
                  font: Arial
                  border:
                    color: '#ffd9fb05'
                    style: dashed # Should we allow styles?
                    left: true
                    right: true
            - Category: 
                equals: Power Tools
                format:
                  fill_color: '#ff35fb05'
                  font_size: 22
                  font: Arial
                  border:
                    color: '#ffd9fb05'
                    style: dashed # Should we allow styles?
                    left: true
                    right: true
```

The above is not meant to be an exhaustive list of all possible formatting functions, but a representation of how to pass from a recipe.

**Comment by ChrisWRWX** [comment]
https://docs.google.com/spreadsheets/d/1iGvxkSTihk4Y_d316INdBzOxB9pWMgBeKTxMtUdCR0s/edit?gid=0#gid=0

**Comment by ChrisWRWX** [comment]
```yml

write:
  - file:
       name:
       formatting:
          columns:
            # index, with slicing
            0:
            '0:5':
            '0,15,25':
            'description':
            'description,long description,lock\, stock and two smoking barrels':
            'desc*,other column': 
            '["", "", ""]': {},
            ${user_selected_columns}: {}
          rows:
           
          cells:
           'A1:D4'
          banding: true/false
          conditionalFormatting: 
```


Banding on clusters...

- No special code!
- Generate a column with e.g. true/false
- Conditional format based on that column.
