### ISSUE TITLE
Optional Columns Broken When Writing to File

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#650]
When using a question mark to allow columns that may or may not exist to be written to a file, the question mark is kept as part of the column name which causes an error.

```yaml
read:
  - test:
      rows: 5
      values:
        Query: Stuff to search

wrangles:
  - python:
      output: New Query
      command: |
        Query + ' site:website.com'

write:
  - file:
      name: temp.xlsx
      columns:
        - Query
        - New Query?
```

![Image](https://github.com/user-attachments/assets/3f134243-1598-4455-a581-135d80f43823)
