### ISSUE TITLE
Split.text Slicing Syntax

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#666]
In the [documentation](https://wrangles.io/python/recipes/wrangles/split#text) we show that it accepts python slicing syntax, yet the following does not work:

```
yaml
wrangles:
  - split.text:
      input: col
      char: ', '
      element: 1:
```

The same goes for wrapping element in square brackets.

**Comment by ChrisWRWX** [comment]
This does work, but the element needs wrapping in quotes to force it to be a string. As is, it's trying to interpret the colon as YAML.



```yml
wrangles:
  - split.text:
      input: col
      char: ', '
      element: '1:'
```

The schema does actually already give examples using quotes. Maybe alter wrangles.io to also make that clear?

`Select a specific element or range after splitting using slicing syntax. e.g. 0, ":5", "5:", "2:8:2"`
