### ISSUE TITLE
Batch and if do not work together with variables

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#675]
This may be tied to issue #619 but I wanted to make sure that it is a known issue with the batch wrangle as well.

Should evaluate to True:
```yaml
wrangles:
  - batch:
      batch_size: 1
      wrangles:
        - create.column:
            output: Variant
            value: ${Variant}
            if: ${Variant} == 'Search Only'
```

The above works without the batch wrangle, but breaks in a batch giving this error:
ValueError: batch - create.column - An error occurred when trying to evaluate if condition '${Variant} == 'Search Only''
