### ISSUE TITLE
Extract max/min value of multiple columns

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#68]
Make an Extract the max value from multiple columns. Pandas `max` function does not allow input columns.
e.g.

| col 1   | col 2                   |  col 3       |
|---:|:----------------------|:---------------|
|  13  | 3  | 26 |

max results:  `26`
maybe also include the column name if desired? -> result:  `col 3: 26`

**Comment by cerdamario13** [comment]
If the input is one column, get max/min from list in column.
|   Values   | 
|:-----|
| [13, 3, 26]  |  

max result: `26`

**Comment by cerdamario13** [comment]
maths can already do not
The input columns must be merged into a list

```yaml
wrangles:
  - maths:
      input: max(col, axis=1)
      output: max
```
