### ISSUE TITLE
Concatenate / Prefix / Suffix  - allow Int / float

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#683]
Get error trying to concat/pre/suffix the batch number with an ID (index). Let's just convert base input and ixes to strings to avoid error.

**Comment by ChrisWRWX** [comment]
Please could you provide some more context to this? A specific example?

All 3 of these functions already coerce the data into a string type before applying the respective function. I'm not able to reproduce the error - I get a string output with '1a' etc. even if the input was a number.

**Comment by ebhills** [comment]
the error happens specifically when suffixing the batch number (I would guess any numeric variable):
```
  - create.index:
      output: My Index
      by: Mfr PN1

  - format.suffix:
        input:
          - My Index
        output: Concat Value
        value: ${batch_number}

```

![Image](https://github.com/user-attachments/assets/6838f7b6-20b8-47aa-8c0b-3b07bc2e7d23)

I think you may have an open issue somewhere about numeric varaibles and defaults. Anyway -- that's the bug.
