### ISSUE TITLE
Make a copy of a column Wrangle

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#69]
When working with data, I have found that some columns have the same data with minor differences, e.g.

|  Item Number in System | Supplier Number| 
|---:|:--------------|
|  AAA-131313 | 131313 | 

if these columns come from a single column source.
then we need two wrangle operations on the same column:
- add AAA prefix
- do nothing but include the column in write wrangle

Make a wrangle that copies a column

```yaml
wrangles:
   - create.column_copy:
       input: Item Number
       output: Item Number in System     # make sure names are different
```

**Comment by cerdamario13** [comment]
used `df[output] = df[input]`

**Comment by cerdamario13** [comment]
This can be done using pandas `copy` function

```yaml
pandas.copy:
  input: col
  output: col_copy
```
