### ISSUE TITLE
Copy Breaks With Multiple Columns and One Duplicate

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#695]
When running a copy wrangle with multiple columns and one of the input columns is repeated, a value error is raised:

```
ValueError: copy - Input and output must be the same length
```

This works:
```
wrangles:
  - copy:
    input:
      - col1
      - col1
    output:
      - col1-copy
      - col1-copy-again
```

But this does not:
```
        wrangles:
        - copy:
            input:
                - col1
                - col2
                - col1
            output:
                - col1-copy
                - col2-copy
                - col1-copy-again
```
