### ISSUE TITLE
All Things WranglesPY Formatting

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPY#700]
This issue is intended to keep track of ideas for types of formatting, how to implement, and how to pass them from a recipe. Please feel free to edit this instead of commenting if you want to add a possibility to the list.

See [here](https://docs.google.com/spreadsheets/d/1iGvxkSTihk4Y_d316INdBzOxB9pWMgBeKTxMtUdCR0s/edit?gid=0#gid=0) for a list of functions.

Current ideas on how to pass from a recipe:
```yaml
write:
  # Basic with a default and columns listed individually
  - file:
      name: tests/temp/write_data.xlsx
      format:
        header_height: 62 # Other options for headers?
        column_width: 40
        row_height: 50
        bold: true
        italic: true
        underline: double
        font: Centaur
        font_size: 14
        font_color: blue 
        fill_color: '#0548fb' # Can also use certain colors by name, to be looked up in a dictionary
        alignment:
          horizontal: right
          vertical: bottom
          wrap_text: true
        col*:
          column_width: 10
          header:
            fill_color: red
            font_size: 14
          fill_color: yellow
          font_size: 18
          font: Algerian
        Not Col:
          width: 18
          header_fill_color: '#ff35fb05'
          font_size: 22
          font: Arial
          border:
            color: '#ffd9fb05'
            style: dashed # Should we allow styles?
            left: true
            right: true


  # Using an external dictionary
  - file:
      name: tests/temp/write_data.xlsx
      format: ${Saved_Format_Dictionary}

  # Column index based formatting
  - file:
      name: tests/temp/write_data.xlsx
      format:
        "index-1:5":
          width: 18
          header_fill_color: '#ff35fb05'
          font_size: 22
          font: Arial
          border:
            color: '#ffd9fb05'
            style: dashed # Should we allow styles?
            left: true
            right: true

  # Conditional formatting using some sort of where
  # Defaults are set as usual
  - file:
      name: tests/temp/write_data.xlsx
      format:
        font: Centaur
        font_size: 14
        font_color: blue 
        fill_color: '#0548fb' # Can also use certain colors by name, to be looked up in a dictionary
        conditional:
          where: 
            - Category: 
                equals: Hand Tools
                format:
                  fill_color: '#ff35fb05'
                  font_size: 22
                  font: Arial
                  border:
                    color: '#ffd9fb05'
                    style: dashed # Should we allow styles?
                    left: true
                    right: true
            - Category: 
                equals: Power Tools
                format:
                  fill_color: '#ff35fb05'
                  font_size: 22
                  font: Arial
                  border:
                    color: '#ffd9fb05'
                    style: dashed # Should we allow styles?
                    left: true
                    right: true
```

The above is not meant to be an exhaustive list of all possible formatting functions, but a representation of how to pass from a recipe.
