### ISSUE TITLE
select.element does not properly handle multiple inputs/outputs

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPY#726]
```
  - select.element:
      input:
        - Most Similar Companies[0]
        - Similarity Scores[0]
      output:
        - Best Match
        - Overall Similarity
      default:
        - {DUNS: --, Company: --, Address: --, City: --, State: --, Zip: --}
        - 0

  - split.dictionary:
      input: Best Match
      output:
        - "*": '* DUNS'
```

When there is no Most Similar Company[0], get this error:

ValueError: split.dictionary - [{'DUNS': '--', 'Company': '--', 'Address': '--', 'City': '--', 'State': '--', 'Zip': '--'}, 0] is not a valid Dictionary

It appears that the output of both inputs is mapped into the first output (Best Match).  Only get this error when the default value is encountered. Not sure why it works when there is a proper dictionary (ie not the default).

repo/data: MDM Customer Matching >> first 100 rows

**Comment by ChrisWRWX** [comment]
Default only allows one value. It doesn't currently support providing a list of values as you're trying there. So your default is itself the list with the dict and 0 for both Best Match and Overall Similarity rather than mapping one to each.

When you subsequently try to split the dictionary that came from the default it receives the list [{ dict }, 0]

You'd need to split it into two wrangles to be able to give them different defaults.

```yml
  - select.element:
      input: Most Similar Companies[0]
      output: Best Match
      default: {DUNS: --, Company: --, Address: --, City: --, State: --, Zip: --}

  - select.element:
      input: Similarity Scores[0]
      output: Overall Similarity
      default: 0
```
