### ISSUE TITLE
Extract attribute/properties output is string

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#73]
When running extract wrangles with propety_type specified (or any other extract), the output is in a list. If there is a need to extract values, an additional wrangle needs to be used

```yaml
- extract.properties:
    input: items
    output: materials
    property_type: materials

- merge.concatenate:
    input: materials
    output: materials_str
    char: ', '
```

output:
|    | items                                    | materials | materials_str|
|---:|:-----------------------------------------|:-----------------------------|:-----------------------|
|  0 | white metal lamp     | ['Metal']               | Metal           |
|  1 | black aluminium lamp | ['Aluminium']               | Aluminium             |
|  2 | blue stainless steel lamp   | ['Stainless Steel'] | Stainless Steel |

Have a way for the output to be just strings (separated by a comma if more than one) like in excel wrangles.
Maybe `return_type: string | list`
Maybe `responseContent: string` for attributes

![image](https://user-images.githubusercontent.com/43070036/186028118-bff83e9d-1d33-4826-a329-5af4d5d465cd.png)

**Comment by cerdamario13** [comment]
```yaml
wrangles:
  - extract.properties:
      input: items
      output: materials
      property_type: materials
      return_data_type: string
```

output:
|    | items                           | materials          |
|---:|:--------------------------------|:-------------------|
|  0 | white metal lamp pvc and copper | PVC, Copper, Metal |
|  1 | black aluminium lamp            | Aluminium          |
|  2 | blue stainless steel lamp       | Stainless Steel    |
|  3 | no materials here               |                    |
