### ISSUE TITLE
When writing data, make sure that values are truly empty

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#74]
When writing data from wrangles and the values come out empty (None, '', NaN) make sure that the value is truly empty. Not just `''`.
Maybe specify using something like `df['DataFrame Column'] = df['DataFrame Column'].fillna(0)`

**Comment by cerdamario13** [comment]
@ChrisWRWX  Wrangle to replace `''` to None, NaN, or any other values?
using:
`df['col'] = df['col'].replace('', None, inplace=False)`

Using recipe does not seem to work

```yaml
  - pandas.replace:
      input: col
      to_replace: 'black'
      value: 'BLACK'
      inplace: False
```

inplace is set to False as default, it is not required

**Comment by cerdamario13** [comment]
@ebhills 

One way to get around the empty string `''` as an output is to use `replace` (pandas function)
```yaml
- pandas.replace:
      input:
        - col
        - col2
      parameters:
        to_replace: ''
        value: Null # output will be None
```

If the output needs to be `NaN`, then numpy needs to be imported using `np.nan`
