### ISSUE TITLE
use eval() to turn strings in recipe to python code (Read Excel file)

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#76]
Files that have headers and then non-important data below and then the actual data. e.g.

| Company |   Number |
|:----------------------------------|------------------:|
| Not important data |             None|
| Not important data |             None|
| Tesla |             19131 |

for now, I can specify headers and use skiprows. But to skip rows 1, 2 (zero based). So I need to use `skiprows: range(1, 3)` and the recipe evaluates that as a string not python code.

Possible Solution: 
`if kwargs.get('skiprows', ''): kwargs['skiprows'] = eval(kwargs['skiprows'])` in file.py - connectors folder

then I could use the following in the recipe:

```yaml
read:
  - file:
      name: 'file_input.xlsx'
      header: 2
      skiprows: range(1, 3)
```
