### ISSUE TITLE
Add wildcard * to Log

### ISSUE THREAD

**Issue by ebhills** [wrangleworks/WranglesPy#78]
Would like to print all columns that start with same name, eg the output of a split.text wrangle. As it stands, I have to declare each one.

Also, may want to allow the same thing in Write output, at least when writing to a file.

**Comment by ChrisWRWX** [comment]
This is because the logic to deal with wildcards is applied to the property named input, which most wrangles use.

It needs altering to cover columns.

**Comment by cerdamario13** [comment]
Added wildcard in log columns
```yaml
wrangles:
  - log:
      columns:
         - Col*   # Will print all Col1, Col2...
```

Added also an escape character
```yaml
wrangles:
  - log:
      column:
        - Col\*  # If there is an column with an asterisk in name it will print only that column
```
