### ISSUE TITLE
Add a today option for date wrangles and for create column-value

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#83]
Add a parameter for all of the date wrangles that allows to use `today` as a value and returns today's date
 
Add also a `today` for create.column that returns today (datetime datatype)

```yaml
wrangles:
  - create.column:
      output: Date Now
      value: today()
```

**Comment by cerdamario13** [comment]
Also to do:

Allow create.column to also use the placeholder values that generate random data from the test connector.

e.g.

```yaml
wrangles:
  - create.column:
      output: column name
      value: <sentence>
```

**Comment by cerdamario13** [comment]
Added the following to create column:
- `_generate_cell_values` function from connector-test to create column. 
- create.column can have today's date (normalized) and random dates from a given range
- allow to give a date as value (normalized)

```yaml
wrangles:
  - create.column:
      output: Random Date
      value: <2022-01-01 to 2022-12-31>
  - create.column:
      output: Today
      value: <date_today>
  - create.column:
      output: Year End
      value: <date 2022-12-31>
```

Data Sample:
| col   | Random Date         | Today               | Year End            |
|:------|:--------------------|:--------------------|:--------------------|
| Hello | 2022-07-03 19:06:37 | 2022-10-03 00:00:00 | 2022-12-31 00:00:00 |
| Fey   | 2022-03-29 07:33:57 | 2022-10-03 00:00:00 | 2022-12-31 00:00:00 |


Will look into adding time to the date. Getting a nanosecond error
