### ISSUE TITLE
wrangles remove duplicate allow strings as inputs

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#84]
Currently, `format.remove_duplicates` only works if the input is a list of strings.
Allow for input to be a string and return the output as a string also

```yaml
wrangles:
 format.remove_duplicates:
   input: Col    # String
   output: Out   # Also a string
```
