### ISSUE TITLE
Filter on Length

### ISSUE THREAD

**Issue by thomasstvr** [wrangleworks/WranglesPy#90]
Could you add a length option to the filter Wrangle?

It would be useful to be able to filter out strings based on their length. Ie selecting only brands which are 4 characters or greater in length.

**Comment by ChrisWRWX** [comment]
Closing this. Able to be done with:

```yaml
wrangles:
  - sql:
      command: |
         SELECT *
         FROM df
         WHERE length( {column} ) > {value}
```

I would like to figure out a nice generic approach to be able to execute simple code and conditions like this, rather than having to add lots of paramters to the filter wrangle.
