### ISSUE TITLE
Add a training connector.

### ISSUE THREAD

**Issue by ChrisWRWX** [wrangleworks/WranglesPy#95]
Add a connector that allows recipes to update DIY wrangles.

e.g.

```yaml
write:
  - train.classify:
      model_id: abc123...

```
