### ISSUE TITLE
Merge two or more dictionaries together Wrangle

### ISSUE THREAD

**Issue by cerdamario13** [wrangleworks/WranglesPy#98]
Merge two or more dictionaries together into one
Similar to `merge.lists`

**Comment by cerdamario13** [comment]
use `merge.dictionaries` to merge two or more dictionaries together

``` yaml
wrangles:
  - merge.dictionaries:
      input:
        - Col1
        - Col2
        - Col3
        - Col4
      output: Output Dict
```
